### ISSUE TITLE
Invalid Java Runtime Configuration

### ISSUE THREAD

**Issue by juicebin** [dantaeusb-mc/Zetter#39] opened 2022-07-11 23:31 UTC
I have no idea if this is even an error with Zetter, but this only happened now that it's installed.
Essentially, I just placed down the easel and started drawing, then after about 10 pixels my game crashed.

**Minecraft Version**: 1.18.2
**Forge Version**: 40.1.60
**Zetter Version**: 0.15.1

**Error Log**: [hs_err_pid29788.log](https://github.com/dantaeusb-mc/Zetter/files/9088115/hs_err_pid29788.log)
**Mod List**: [modlist.txt](https://github.com/dantaeusb-mc/Zetter/files/9088118/modlist.txt)

Here are the steps to reproduce, although maybe not needed.

**Steps to reproduce**:
1.) Be in new world, creative mode
2.) Place down easel
3.) Place down artist's table next to it
4.) Place paints in easel
5.) Place canvas in easel
6.) Start drawing on easel

**Comment by juicebin** [comment] 2022-07-11 23:38
Doesn't seem to happen on the 1.16.0 beta

**Comment by dantaeusb** [comment] 2022-07-12 00:05
Yes, I can confirm from the logs that it's caused by Zetter: seems like on the lower level it can't update texture of the canvas on client. The error is quite unusual, and I can't say that in 1.16.0/1.18.2 the way painting textures working are different. Could also be a compatibility issue. I'll try to reproduce that.

By the way, do you have any problems with maps on your modpack? The way paintings work is very similar.

**Comment by dantaeusb** [comment] 2022-07-12 01:15
I have an idea how it might have happened and why it's rare. Probably not related to other mods, working on it. I assume you were looking away from the Easel when drawing. Quite an interesting thing happens under such conditions.

**Comment by dantaeusb** [comment] 2022-07-12 02:01
I assume it should be fixed in 0.15.2, which should be available on CurseForge soon. Yet the way your game crashed is quite unusual, so it could be actually caused by another mod, which caused Zetter to throw an even more serious error that stopped Minecraft.

I'm removing critical status and waiting for feedback if the issue happen again.

**Closed** 2023-02-19 02:12 UTC
Labels: bug
